/* British Facebook CMS v2 — local template renderer */
const BF={products:[],outputs:[],templates:[],settings:{brand:'British Propolis',footer:'100% Propolis Asli Inggris'}};
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hexToRgb=h=>{h=h.replace('#','');return {r:parseInt(h.slice(0,2),16),g:parseInt(h.slice(2,4),16),b:parseInt(h.slice(4,6),16)}};
function dominant(img){const c=document.createElement('canvas'),x=c.getContext('2d');c.width=c.height=48;x.drawImage(img,0,0,48,48);let d=x.getImageData(0,0,48,48).data,r=0,g=0,b=0,n=0;for(let i=0;i<d.length;i+=16){r+=d[i];g+=d[i+1];b+=d[i+2];n++}return '#'+[r,g,b].map(v=>Math.round(v/n).toString(16).padStart(2,'0')).join('')}
function rr(c,x,y,w,h,r){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function fit(img,maxW,maxH){const s=Math.min(maxW/img.naturalWidth,maxH/img.naturalHeight);return [img.naturalWidth*s,img.naturalHeight*s]}
function drawText(c,o,s,vars){let text=(o.content||'').replace(/\{\{(.*?)\}\}/g,(_,k)=>vars[k.trim()]??'');c.save();c.translate(o.x*s,o.y*s);c.rotate((o.rotation||0)*Math.PI/180);c.globalAlpha=o.opacity??1;c.textAlign=o.align||'left';c.textBaseline='middle';c.font=`${o.weight||700} ${o.size*s}px ${o.font||'Poppins'}`;if(o.shadow){c.shadowColor=o.shadowColor||'rgba(0,0,0,.35)';c.shadowBlur=(o.shadowBlur||10)*s;c.shadowOffsetX=(o.shadowX||2)*s;c.shadowOffsetY=(o.shadowY||3)*s}if(o.stroke){c.strokeStyle=o.stroke;c.lineWidth=(o.strokeWidth||2)*s;c.strokeText(text,0,0)}c.fillStyle=o.color||'#fff';c.fillText(text,0,0);c.restore()}
function drawBadge(c,o,s,vars){let text=(o.text||'PROMO').replace(/\{\{(.*?)\}\}/g,(_,k)=>vars[k.trim()]??'');const w=(o.width||220)*s,h=(o.height||70)*s,x=o.x*s,y=o.y*s;c.save();c.translate(x,y);c.rotate((o.rotation||-2)*Math.PI/180);c.globalAlpha=o.opacity??1;c.fillStyle=o.color||'#d51d29';c.shadowColor='rgba(0,0,0,.22)';c.shadowBlur=12*s;c.shadowOffsetY=5*s;rr(c,0,0,w,h,h*.45);c.fill();c.shadowColor='transparent';c.fillStyle=o.textColor||'#fff';c.font=`800 ${Math.min(28*s,h*.38)}px ${o.font||'Poppins'}`;c.textAlign='center';c.textBaseline='middle';c.fillText(text,w/2,h/2);c.restore()}
function drawShape(c,o,s){c.save();c.globalAlpha=o.opacity??1;c.fillStyle=o.fill||'#fff';c.strokeStyle=o.stroke||'transparent';c.lineWidth=(o.strokeWidth||0)*s;if(o.shape==='circle'){c.beginPath();c.arc(o.x*s,o.y*s,(o.radius||90)*s,0,Math.PI*2);c.fill();c.stroke()}else if(o.shape==='roundRect'){rr(c,o.x*s,o.y*s,(o.width||300)*s,(o.height||120)*s,(o.radius||30)*s);c.fill();c.stroke()}else if(o.shape==='line'){c.fillRect(o.x*s,o.y*s,(o.width||400)*s,(o.height||8)*s)}else if(o.shape==='burst'){c.beginPath();for(let i=0;i<24;i++){let a=i*Math.PI/12,r=(i%2?70:100)*s,xx=o.x*s+Math.cos(a)*r,yy=o.y*s+Math.sin(a)*r;i?c.lineTo(xx,yy):c.moveTo(xx,yy)}c.closePath();c.fill()}c.restore()}
function renderTemplate(img,t,extra={}){const size=+q('#size').value||1080,c=document.createElement('canvas');c.width=c.height=size;const x=c.getContext('2d'),base=dominant(img),vars={product_name:q('#productName').value||'British Propolis',headline:q('#headline').value||'Propolis Terbaik',subline:q('#subline').value||'100% Propolis Asli Inggris',promo:q('#promoText')?.value||'PROMO',price:q('#priceText')?.value||'',brand:BF.settings.brand,footer:BF.settings.footer,...extra};let bg=t.background||{};if(bg.mode==='adaptive'){const rgb=hexToRgb(base);const g=x.createLinearGradient(0,0,size,size);g.addColorStop(0,`rgb(${rgb.r},${rgb.g},${rgb.b})`);g.addColorStop(1,'#101412');x.fillStyle=g}else{const g=x.createLinearGradient(0,0,size,size);g.addColorStop(0,bg.start||'#8e0f0f');g.addColorStop(1,bg.end||'#3d0707');x.fillStyle=g}x.fillRect(0,0,size,size);for(const o of t.layers||[]){if(o.type==='text')drawText(x,o,size/1080,vars);else if(o.type==='badge')drawBadge(x,o,size/1080,vars);else if(o.type==='shape')drawShape(x,o,size/1080);else if(o.type==='product'){const [w,h]=fit(img,(o.maxWidth||540)*size/1080,(o.maxHeight||600)*size/1080);x.save();x.translate(o.x*size/1080,o.y*size/1080);x.rotate((o.rotation||0)*Math.PI/180);if(o.shadow){x.shadowColor='rgba(0,0,0,.28)';x.shadowBlur=25*size/1080;x.shadowOffsetY=12*size/1080}x.drawImage(img,-w/2,-h/2,w,h);x.restore()}}return c}
function populateTemplates(){BF.templates=window.BF_TEMPLATES||[];q('#templateChecks').innerHTML=BF.templates.map(t=>`<label><input type="checkbox" value="${t.id}" checked> ${t.name}</label>`).join('');q('#templateCards').innerHTML=BF.templates.map(t=>`<div class="template-card"><div class="template-thumb" style="background:${t.preview||'#8e0f0f'}">${t.name.slice(0,2).toUpperCase()}</div><b>${t.name}</b><small>${t.description||''}</small></div>`).join('')}
function selectedTemplates(){const ids=new Set(qa('#templateChecks input:checked').map(x=>x.value));return BF.templates.filter(t=>ids.has(t.id))}
function addFiles(files){[...files].filter(f=>/^image\/(png|jpeg|webp)$/.test(f.type)).forEach(f=>{const url=URL.createObjectURL(f),img=new Image;img.onload=()=>{BF.products.push({img,name:f.name,url,dominant:dominant(img)});renderProducts()};img.src=url})}
function renderProducts(){q('#productList').innerHTML=BF.products.map((p,i)=>`<div class="product-item"><button class="remove" data-i="${i}">×</button><img src="${p.url}"><small>${p.name}</small></div>`).join('');qa('.product-item .remove').forEach(b=>b.onclick=()=>{BF.products.splice(+b.dataset.i,1);renderProducts()})}
function preview(){if(!BF.products.length)return alert('Upload minimal satu gambar.');q('#previewGrid').innerHTML='';selectedTemplates().forEach(t=>{const c=renderTemplate(BF.products[0].img,t),d=document.createElement('div');d.className='preview-card';d.append(c,Object.assign(document.createElement('div'),{textContent:t.name}));q('#previewGrid').append(d)})}
async function generateAll(){if(!BF.products.length)return alert('Upload minimal satu gambar.');const ts=selectedTemplates();if(!ts.length)return alert('Pilih minimal satu template.');BF.outputs=[];let total=BF.products.length*ts.length,n=0;q('#progress').classList.remove('hidden');for(const p of BF.products)for(const t of ts){const c=renderTemplate(p.img,t),blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.93));BF.outputs.push({blob,name:p.name.replace(/\.[^.]+$/,'')+'-'+t.id+'.jpg'});n++;q('#progressBar').style.width=Math.round(n/total*100)+'%';q('#progressText').textContent=Math.round(n/total*100)+'%';await new Promise(r=>setTimeout(r,0))}q('#downloadBtn').disabled=false;preview()}
async function downloadZip(){if(!BF.outputs.length)return;const z=new JSZip;BF.outputs.forEach(x=>z.file(x.name,x.blob));const b=await z.generateAsync({type:'blob'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='british-facebook-images.zip';a.click()}
function init(){BF.settings.brand=localStorage.bfBrand||'British Propolis';BF.settings.footer=localStorage.bfFooter||'100% Propolis Asli Inggris';q('#brandSetting').value=BF.settings.brand;q('#footerSetting').value=BF.settings.footer;populateTemplates();q('#fileInput').onchange=e=>addFiles(e.target.files);q('#dropzone').ondragover=e=>e.preventDefault();q('#dropzone').ondrop=e=>{e.preventDefault();addFiles(e.dataTransfer.files)};q('#previewBtn').onclick=preview;q('#generateBtn').onclick=generateAll;q('#downloadBtn').onclick=downloadZip;q('#clearProducts').onclick=()=>{BF.products=[];renderProducts()};q('#saveSettings').onclick=()=>{BF.settings.brand=q('#brandSetting').value;BF.settings.footer=q('#footerSetting').value;localStorage.bfBrand=BF.settings.brand;localStorage.bfFooter=BF.settings.footer;q('#savedMsg').textContent='Pengaturan tersimpan di browser.'};qa('.nav').forEach(b=>b.onclick=()=>{qa('.view').forEach(v=>v.classList.remove('active'));q('#'+b.dataset.view).classList.add('active');qa('.nav').forEach(n=>n.classList.toggle('active',n===b))})}window.addEventListener('DOMContentLoaded',init);