/* British Facebook — Canva-style visual editor. Local only. */
let BFEditor=null;
const E=s=>document.querySelector(s);
function bfSel(){return BFEditor?.getActiveObject()}
function bfApply(){const o=bfSel();if(!o)return;const font=E('#edFont')?.value||'Poppins',size=+E('#edSize')?.value||40,color=E('#edColor')?.value||'#ffffff',effect=E('#edEffect')?.value||'none';if(o.type==='i-text'||o.type==='textbox'){o.set({fontFamily:font,fontSize:size,fill:color,fontWeight:E('#edBold')?.checked?'800':'400',fontStyle:E('#edItalic')?.checked?'italic':'normal',underline:E('#edUnderline')?.checked});if(effect==='outline')o.set({stroke:color,strokeWidth:Math.max(1,size*.035),paintFirst:'stroke'});else{o.set({stroke:null,strokeWidth:0,paintFirst:'fill'});if(effect==='shadow')o.set({shadow:new fabric.Shadow({color:'rgba(0,0,0,.35)',blur:size*.12,offsetX:size*.04,offsetY:size*.05})});else if(effect==='strong')o.set({shadow:new fabric.Shadow({color:'rgba(0,0,0,.7)',blur:size*.04,offsetX:size*.035,offsetY:size*.06})});else if(effect==='glow')o.set({shadow:new fabric.Shadow({color:color,blur:size*.18,offsetX:0,offsetY:0})});else o.set({shadow:null})}}else if(o.set)o.set({fill:color});o.set({opacity:(+E('#edOpacity')?.value||100)/100,angle:+E('#edRotate')?.value||0});BFEditor.renderAll()}
function bfAddText(text='Headline Anda'){const o=new fabric.Textbox(text,{left:90,top:100,width:520,fontFamily:'Poppins',fontSize:64,fontWeight:'800',fill:'#fff',lineHeight:1.05,editable:true});BFEditor.add(o).setActiveObject(o);BFEditor.renderAll()}
function bfAddShape(kind){let o;if(kind==='circle')o=new fabric.Circle({radius:90,left:700,top:150,fill:'#d51d29',opacity:.85});if(kind==='round')o=new fabric.Rect({width:300,height:150,left:680,top:650,rx:40,ry:40,fill:'#d51d29'});if(kind==='line')o=new fabric.Rect({width:420,height:8,left:90,top:500,fill:'#fff',rx:4,ry:4});if(kind==='sticker')o=new fabric.Group([new fabric.Circle({radius:70,originX:'center',originY:'center',fill:'#f5b51b'}),new fabric.Text('PROMO',{originX:'center',originY:'center',fontFamily:'Montserrat',fontSize:24,fontWeight:'800',fill:'#fff'})],{left:760,top:760});if(o)BFEditor.add(o).setActiveObject(o).renderAll()}
function bfAddProduct(file){const rd=new FileReader;rd.onload=e=>fabric.Image.fromURL(e.target.result,img=>{const max=560,scale=Math.min(max/img.width,max/img.height);img.set({left:470,top:270,scaleX:scale,scaleY:scale,originX:'center',originY:'center'});BFEditor.add(img).setActiveObject(img).renderAll()});rd.readAsDataURL(file)}
function bfBackground(c){BFEditor.setBackgroundColor(c,()=>BFEditor.renderAll())}
function bfPreset(name){BFEditor.clear();const palettes={red:['#8e0f0f','#ed351b','#fff'],green:['#123d2d','#5f9f52','#fff'],blue:['#082b55','#2f7ebd','#fff'],gold:['#11100d','#3b3020','#f2cf76'],cream:['#f5f0e7','#fff','#17324d']};const p=palettes[name]||palettes.red;BFEditor.setBackgroundColor(p[0],()=>{});const g=new fabric.Rect({left:0,top:0,width:1080,height:1080,fill:p[1],opacity:.55,selectable:false,evented:false});BFEditor.add(g);const title=new fabric.Textbox('SUPLEMEN UNTUK\nKESEHATAN KELUARGA',{left:90,top:100,width:700,fontFamily:'Anton',fontSize:72,fontWeight:'400',fill:p[2],lineHeight:1.02});BFEditor.add(title);const sub=new fabric.Textbox('BRITISH PROPOLIS\nPure British Propolis',{left:90,top:285,width:430,fontFamily:'Montserrat',fontSize:34,fontWeight:'800',fill:p[2],lineHeight:1.1});BFEditor.add(sub);const badge=new fabric.Group([new fabric.Rect({width:350,height:90,rx:35,ry:35,fill:'#f5b51b',originX:'center',originY:'center'}),new fabric.Text('PROMO / HARGA',{fontFamily:'Poppins',fontSize:27,fontWeight:'800',fill:'#fff',originX:'center',originY:'center'})],{left:90,top:820});BFEditor.add(badge);BFEditor.renderAll()}
function bfDuplicate(){const o=bfSel();if(!o)return;o.clone(c=>{c.set({left:(o.left||0)+25,top:(o.top||0)+25});BFEditor.add(c).setActiveObject(c).renderAll()})}
function bfInit(){const el=E('#bfCanvas');if(!el||typeof fabric==='undefined')return;BFEditor=new fabric.Canvas(el,{width:1080,height:1080,preserveObjectStacking:true,selection:true});bfBackground('#a50f0f');bfAddText('Headline Anda');E('#edFile')?.addEventListener('change',e=>e.target.files[0]&&bfAddProduct(e.target.files[0]));E('#edAddText')?.addEventListener('click',()=>bfAddText());E('#edCircle')?.addEventListener('click',()=>bfAddShape('circle'));E('#edRound')?.addEventListener('click',()=>bfAddShape('round'));E('#edLine')?.addEventListener('click',()=>bfAddShape('line'));E('#edSticker')?.addEventListener('click',()=>bfAddShape('sticker'));E('#edDelete')?.addEventListener('click',()=>{const o=bfSel();if(o){BFEditor.remove(o);BFEditor.discardActiveObject().renderAll()}});E('#edDuplicate')?.addEventListener('click',bfDuplicate);E('#edFront')?.addEventListener('click',()=>{const o=bfSel();if(o)BFEditor.bringForward(o).renderAll()});E('#edBack')?.addEventListener('click',()=>{const o=bfSel();if(o)BFEditor.sendBackwards(o).renderAll()});['#edFont','#edSize','#edColor','#edBold','#edItalic','#edUnderline','#edOpacity','#edRotate','#edEffect'].forEach(q=>E(q)?.addEventListener('input',bfApply));E('#edBg')?.addEventListener('input',e=>bfBackground(e.target.value));$$('#editor .ed-preset').forEach(b=>b.addEventListener('click',()=>bfPreset(b.dataset.preset)));E('#edExport')?.addEventListener('click',()=>{BFEditor.discardActiveObject();BFEditor.renderAll();const a=document.createElement('a');a.download='british-propolis-design.png';a.href=BFEditor.toDataURL({format:'png',multiplier:1});a.click()});BFEditor.on('selection:created',bfSync);BFEditor.on('selection:updated',bfSync)}
function bfSync(){const o=bfSel();if(!o)return;if(E('#edFont'))E('#edFont').value=o.fontFamily||'Poppins';if(E('#edSize'))E('#edSize').value=Math.round(o.fontSize||40);if(E('#edOpacity'))E('#edOpacity').value=Math.round((o.opacity??1)*100);if(E('#edRotate'))E('#edRotate').value=Math.round(o.angle||0);if(E('#edColor')&&typeof o.fill==='string'&&o.fill[0]==='#')E('#edColor').value=o.fill}
function $$(s){return[...document.querySelectorAll(s)]}
window.addEventListener('DOMContentLoaded',()=>{const nav=$$('.nav'),views=$$('.view');nav.forEach(b=>{b.addEventListener('click',()=>{if(b.dataset.view==='editor'){views.forEach(v=>v.classList.remove('active'));E('#editor').classList.add('active');nav.forEach(n=>n.classList.toggle('active',n===b));setTimeout(()=>BFEditor||bfInit(),50)}})});if(E('#editor'))bfInit()});